// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// return_port_cpp
arma::vec return_port_cpp(arma::mat R, arma::vec weights);
RcppExport SEXP CoreHF_return_port_cpp(SEXP RSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(return_port_cpp(R, weights));
    return rcpp_result_gen;
END_RCPP
}
// return_annualized_cpp
double return_annualized_cpp(arma::vec r, double freq);
RcppExport SEXP CoreHF_return_annualized_cpp(SEXP rSEXP, SEXP freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type freq(freqSEXP);
    rcpp_result_gen = Rcpp::wrap(return_annualized_cpp(r, freq));
    return rcpp_result_gen;
END_RCPP
}
// std_cpp
double std_cpp(arma::vec r);
RcppExport SEXP CoreHF_std_cpp(SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(std_cpp(r));
    return rcpp_result_gen;
END_RCPP
}
// analyzePorts_cpp
NumericMatrix analyzePorts_cpp(const arma::mat R, const arma::mat ports, const double freq);
RcppExport SEXP CoreHF_analyzePorts_cpp(SEXP RSEXP, SEXP portsSEXP, SEXP freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type ports(portsSEXP);
    Rcpp::traits::input_parameter< const double >::type freq(freqSEXP);
    rcpp_result_gen = Rcpp::wrap(analyzePorts_cpp(R, ports, freq));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP CoreHF_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP CoreHF_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP CoreHF_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP CoreHF_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_sum
double rcpparma_sum(const arma::colvec& x);
RcppExport SEXP CoreHF_rcpparma_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_sum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"CoreHF_return_port_cpp", (DL_FUNC) &CoreHF_return_port_cpp, 2},
    {"CoreHF_return_annualized_cpp", (DL_FUNC) &CoreHF_return_annualized_cpp, 2},
    {"CoreHF_std_cpp", (DL_FUNC) &CoreHF_std_cpp, 1},
    {"CoreHF_analyzePorts_cpp", (DL_FUNC) &CoreHF_analyzePorts_cpp, 3},
    {"CoreHF_rcpparma_hello_world", (DL_FUNC) &CoreHF_rcpparma_hello_world, 0},
    {"CoreHF_rcpparma_outerproduct", (DL_FUNC) &CoreHF_rcpparma_outerproduct, 1},
    {"CoreHF_rcpparma_innerproduct", (DL_FUNC) &CoreHF_rcpparma_innerproduct, 1},
    {"CoreHF_rcpparma_bothproducts", (DL_FUNC) &CoreHF_rcpparma_bothproducts, 1},
    {"CoreHF_rcpparma_sum", (DL_FUNC) &CoreHF_rcpparma_sum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CoreHF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
