# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

return_port_cpp <- function(R, weights) {
    .Call('CoreHF_return_port_cpp', PACKAGE = 'CoreHF', R, weights)
}

return_annualized_cpp <- function(r, freq = 12) {
    .Call('CoreHF_return_annualized_cpp', PACKAGE = 'CoreHF', r, freq)
}

std_cpp <- function(r) {
    .Call('CoreHF_std_cpp', PACKAGE = 'CoreHF', r)
}

analyzePorts_cpp <- function(R, ports, freq = 12) {
    .Call('CoreHF_analyzePorts_cpp', PACKAGE = 'CoreHF', R, ports, freq)
}

rcpparma_hello_world <- function() {
    .Call('CoreHF_rcpparma_hello_world', PACKAGE = 'CoreHF')
}

rcpparma_outerproduct <- function(x) {
    .Call('CoreHF_rcpparma_outerproduct', PACKAGE = 'CoreHF', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('CoreHF_rcpparma_innerproduct', PACKAGE = 'CoreHF', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('CoreHF_rcpparma_bothproducts', PACKAGE = 'CoreHF', x)
}

rcpparma_sum <- function(x) {
    .Call('CoreHF_rcpparma_sum', PACKAGE = 'CoreHF', x)
}

